### PR TITLE
Adding new features and solve test fails

### PR DESCRIPTION
**Pull request by cgmpinos**
I have added the div and mod operators for integer numbers for #88.
calculator

### CODE REVIEW

**Comment by cgmpinos** [comment]
I have also 
1) added pi button (since the calculator has sin,cos and tan functions, i think pi button would be necessary)
2) added x factorial (x!) operation and the necessary tests to check its function
3) solved the tests of sin, cos and tan that failed (sin, cos and tan did not calculate the right results, so i removed Math.toRadians function and now the tests, which were not written by me, pass)
calculator2

**Comment by pH-7** [comment]
Hi @cgmpinos

Thanks very much for those changes! I really appreciate your time improving the calculator!! 💯

Could you just let me know on what Java version you have tested your changes?

Can you also commit `SimpleJavaCalculator.jar` containing your new changes, and run it?

To do so, you can generate a new jar file with the following CLI command when you are in the `src/` directory `jar cmvf ../manifest.mf ../SimpleJavaCalculator.jar simplejavacalculator/*.class`

**Comment by pH-7** [comment]
Hi @cgmpinos

Thanks very much for those changes! I really appreciate your time improving the calculator!! 💯

Could you just let me know on what Java version you have tested your changes?

Can you also commit `SimpleJavaCalculator.jar` containing your new changes, and run it?

To do so, you can generate a new jar file with the following CLI command when you are in the `src/` directory `jar cmvf ../manifest.mf ../SimpleJavaCalculator.jar simplejavacalculator/*.class`

**Comment by pH-7** [comment]
Let me know @cgmpinos when you can get back to this. That way, I will be able to approve and merge your work to the main branch.

Thanks!
Have a great day!

**Comment by pH-7** [comment]
Hey @cgmpinos, 

Hope you are still doing well!

I’ve noticed you have two very minor conflicts to be fixed 🙂 Just give me a shout when all done.


Have a great Friday!🎉

**Pull request closed without merging**
