### PR TITLE
Make the text-area more Comprehensive

### PR DESCRIPTION
**Pull request by Usamaahmad751**
Users can add any text through the keyboard in the text-area field and applications stop further working. That's not comprehensive, So I put applied the function setEditable(false) on text-area to prevent any input data from the keyboard users can only hit calculator buttons to calculate the data.

### CODE REVIEW

**Comment by pH-7** [comment]
Umh, interesting one! Should we really allow users editing numbers directly through the text area...? And what would happen if letters would be added instead of digits..? Have you been thinking about most of the possible possibilities?

Anyway, I really appreciate this and I'm looking forward to hearing your thoughts! Thanks again!

**Comment by Usamaahmad751** [comment]
For now, I added the code of line to prevent the user to enter data into the text area directly from their keyboard. The solution is that we only allow the user to enter only numeric values in text-area. So we will not get any NaN value and hence our calculator can perform the exact calculations purely based on numbers.

**Comment by pH-7** [comment]
Awesome! Thanks very much for those details @Usamaahmad751! On what Java version have you testing the changes?

**Comment by pH-7** [comment]
@Usamaahmad751 On what Java version have you tested the changes?

**Comment by pH-7** [comment]
`text.setEditable(false);` has now been added, through #30, https://github.com/pH-7/Simple-Java-Calculator/pull/30/files#diff-16347d59723678eb180c3e428db15d80R120

Thanks anyway @Usamaahmad751  I really appreciated your help and you are very welcome for any further contributions! 🤗

**Pull request closed without merging**
