### PR TITLE
Added "bin" button to show the result as binary

### PR DESCRIPTION
**Pull request by SidaDan**
Hi,
maybe could be helpfully to know the result as binary.

Regards Frank

### CODE REVIEW

**Comment by pH-7** [comment]
Thanks a lot for your contribution @SidaDan 
Are all buttons displaying well? Can you send a screenshot?

**Comment by pH-7** [comment]
Last thing :), you have a conflict with UI.java 😕

**Comment by SidaDan** [comment]
> 
> 
> Thanks a lot for your contribution @SidaDan
> Are all buttons displaying well? Can you send a screenshot?

Yes and Yes.

will check it again.

grafik

**Comment by pH-7** [comment]
Let me know if you want me to fix your conflict...? I will come back to you by Tuesday if the conflict is still there :)

**Comment by SidaDan** [comment]
That would be nice, because I go for 2 weeks in vacation :)

**Comment by pH-7** [comment]
No worries @SidaDan. Enjoy your vacation! I hope you have a great time!
Apparently, the branch you were working on wasn't updated for a while. That's why you got conflicts. I fixed the it by now :)

**Pull request merged**
