### PR TITLE
New ln (natural logarithm) button is created

### PR DESCRIPTION
**Pull request by af4092**
1. I've added new button for the Calculator: ln (natural logarithm)
2. I made changes on UI.java by adding:
                        line 55: butln;
                        line 105: butln = new JButton("ln"); 
                        line 141: butln.setFont(font); 
                        line 179: panelSub5.add(butln); 
                        line 213: butln.addActionListener(this); 
                        line 293-294: if (source == butln)
                                   writer(calc.calculateMono(Calculator.MonoOperatorModes.ln, reader())); 
3. Changes on Calculator.java:
                        line 26: ln;
                        line 116-117: if (newMode == MonoOperatorModes.ln) {
                                                       return log(num); }

This is the result after update: 
image

### CODE REVIEW

**Comment by af4092** [comment]
Hello, 

This is my first contribution to Github open source. So let me know if anything else I can do. I'm still on the learning process, I hope by being able to contribute I can improve my skills. 

Thank you

**Comment by af4092** [comment]
Anyone going to review my request :)

**Comment by pH-7** [comment]
Hi @af4092 

> This is my first contribution to Github open source. 

Congratulations! I'm very glad you decided to choose this project as your first contribution! It definitely makes my day! 😊

>  So let me know if anything else I can do. 

Your description is well detailed! Clear and neat.

**Comment by pH-7** [comment]
@af4092 Could you just let me know on what Java version you have tested your changes?

Can you also commit `SimpleJavaCalculator.jar` containing your new changes, and run it?

To do so, you can generate a new jar file with the following CLI command when you are in the `src/` directory `jar cmvf ../manifest.mf ../SimpleJavaCalculator.jar simplejavacalculator/*.class`


Thanks very much, once again, for this! I really appreciate your kind contribution! 😊

**Comment by af4092** [comment]
@pH-7 Hello, thank you for your reply
1. Java version is 19.0.2
2. I couldn't run the CLI command to generate jar file, I think I need to learn more about it, instead I did run check it in the Eclipse IDE, and used its export function to create runnable jar file. So if it's not what you are expecting, I would be glad if you could explain more in detail, so that I can correct and learn myself.
Thank you

This is the jar file that I've created on Eclipse IDE:

image

**Comment by pH-7** [comment]
Fair enough @af4092! 🙂  The commands are pretty straightforward. I'm sure very soon you will be able to generate one. Let me know if you need any help concerning it.
Anyway, I will approve this PR for now, and if get the `jar` archive compiled, feel free to raise a new Pull Request with the new `SimpleJavaCalculator.jar`


Have a wonderful day! Take care 🙂

**Review by pH-7 — APPROVED** [review]

**Pull request merged**
