### PR TITLE
Move the calculation logics into a separate file

### PR DESCRIPTION
**Pull request by hczhcz**

### CODE REVIEW

**Comment by pH-7** [comment]
Hey @hczhcz! Thanks for the contribution! Seems good. I'm not able to test it right now. Did you test it? (and on what Java version?). Is that works well?

**Comment by hczhcz** [comment]
Hey :) It seems work correctly. But I have not do detailed testing yet.

We (@PSharon7 @cc2333 @lynprogram and me) will [test it with JUnit](https://github.com/hczhcz/Java-Calculator-JUnit-Example) soon. We need a simple Java project to demonstrate some software testing techniques so I forked this project.

Java Environment:

    # java -version    
    java version "1.7.0_79"
    OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.15.04.1)
    OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by pH-7** [comment]
Hey @hczhcz (and @PSharon7 @cc2333 @lynprogram), okay that would be great. Really happy :smile_cat: 
Please let me know. Have a great day

**Comment by hczhcz** [comment]
Test done [here](https://github.com/hczhcz/Java-Calculator-JUnit-Example).

**Comment by pH-7** [comment]
Awesome!! That's a lot  @hczhcz and @PSharon7 @cc2333 @lynprogram

**Pull request merged**
