### PR TITLE
Added unit tests for the calculator class.

### PR DESCRIPTION
**Pull request by erickjrogers**
Hi, I'm learning to make unit tests for a project I'm doing, so I thought I'd write some tests for your calculator. Let me know if you have any suggestions.

### CODE REVIEW

**Comment by pH-7** [comment]
Great! Tests are indeed more than welcome. I feel bad there aren't any unit tests for the moment. 
I initially created this project without too much time, that was 8 years ago! Units tests are really important nowadays and I'm so glad you brought them in your PR.

**Comment by pH-7** [comment]
By the way, could you copy/paste the output test results from the terminal to here?

**Comment by pH-7** [comment]
By the way @erickjrogers, could you copy/paste the output test results from the terminal to here?

**Comment by erickjrogers** [comment]
> By the way @erickjrogers, could you copy/paste the output test results from the terminal to here?

Here's the .xml output from eclipse in a zip, the console didn't display anything because all the tests passed.

[CalculatorTest 20200504-102221.zip](https://github.com/pH-7/Simple-Java-Calculator/files/4575544/CalculatorTest.20200504-102221.zip)

**Comment by pH-7** [comment]
> > By the way @erickjrogers, could you copy/paste the output test results from the terminal to here?
> 
> @pH-7 Here's the .xml output from eclipse in a zip, the console didn't display anything because all the tests passed.
> 
> [CalculatorTest 20200504-102221.zip](https://github.com/pH-7/Simple-Java-Calculator/files/4575544/CalculatorTest.20200504-102221.zip)

Awesome. It was just for the record. Thanks again. Looking forward to seeing further other great things from you! 🤗

**Pull request merged**
