### PR TITLE
Removed the issue

### PR DESCRIPTION
**Pull request by TechDevSubhopriyo**
I have put a check if num2 is zero, then the num1 will be returned after addition.
I have also added a check for Math.tan

### CODE REVIEW

**Comment by pH-7** [comment]
Thanks very much for fixing this @TechDevSubhopriyo 
Really appreciate it. 

Before I can approve it, can you exclude the IntelliJ's **config files** and its **.iml file**.

I would like to see only the *.java files here :)

**Comment by TechDevSubhopriyo** [comment]
> Thanks very much for fixing this @TechDevSubhopriyo
> Really appreciate it.
> 
> Before I can approve it, can you exclude the IntelliJ's **config files** and its **.iml file**.
> 
> I would like to see only the *.java files here :)

Surely

**Comment by pH-7** [comment]
> > Thanks very much for fixing this @TechDevSubhopriyo
> > Really appreciate it.
> > Before I can approve it, can you exclude the IntelliJ's **config files** and its **.iml file**.
> > I would like to see only the *.java files here :)
> 
> Surely

Great! Let me know once you I've done it then :)

**Comment by pH-7** [comment]
Hey @TechDevSubhopriyo 

I hope everything is going great for you!

I was wondering today if you got the chance to read my above comments?

Thanks!

**Comment by pH-7** [comment]
Hey @TechDevSubhopriyo  

Could you re-test and rereview this one, since it's yours. Thanks!

**Pull request merged**
